version: "3.3"
services:
 token_migration_backend_app :
    container_name: token_migration_backend_app
    image: token_migration-backend-app:v1.0
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "8100:8100"
    volumes:
      - .:/server
    command: npm run start-dev
    depends_on:
      - token_migration_mongo_db
      - token_migration_redis_db
    restart: always

 token_migration_mongo_db:
    container_name: token_migration-mongo-db
    image: "mongo:latest"
    restart: always
    ports:
      - 27017:27017
    volumes:
      - token_migration:/data/db
  
 mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8500:8081
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://token_migration_mongo_db:27017/tokenMigration

 token_migration_redis_db:
    container_name: token_migration-redis-db
    image: "redis:alpine"
    restart: always
    ports:
      - "6380:6379"

 token_migration_redis_commander:
    container_name: token_migration-redis-commander
    image: "rediscommander/redis-commander:latest"
    restart: always
    environment:
    - REDIS_HOSTS=local:token_migration_redis_db
    ports:
    - "5052:8081"

volumes:
  token_migration: